version: "3.9"

services:
  carrito:
    image: ${ECR_REGISTRY}/carrito:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  core:
    image: ${ECR_REGISTRY}/core:latest
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  usuarios:
    image: ${ECR_REGISTRY}/usuarios:latest
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
#sas