version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: hh_mysql_local
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "db_huertohogar"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  carrito:
    build:
      context: ./carrito-microservice
      dockerfile: Dockerfile
    image: carrito-service:local
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_huertohogar
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      mysql:
        condition: service_healthy

  core:
    build:
      context: ./core-microservicio
      dockerfile: Dockerfile
    image: core-service:local
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_huertohogar
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      mysql:
        condition: service_healthy

  usuarios:
    build:
      context: ./MicroUsuarios/MicroUsuarios
      dockerfile: Dockerfile
    image: usuarios-service:local
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_huertohogar
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
