name: CI-CD Backend AWS

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      ###############################################################
      # 1. BUILD CARRITO
      ###############################################################
      - name: Build carrito JAR
        run: |
          cd carrito-microservice
          mvn -B package -DskipTests

      - name: Build carrito Docker image
        run: docker build -t ${{ secrets.ECR_REGISTRY }}/carrito:latest ./carrito-microservice

      ###############################################################
      # 2. BUILD CORE
      ###############################################################
      - name: Build core JAR
        run: |
          cd core-microservicio
          mvn -B package -DskipTests

      - name: Build core Docker image
        run: docker build -t ${{ secrets.ECR_REGISTRY }}/core:latest ./core-microservicio

      ###############################################################
      # 3. BUILD USUARIOS
      ###############################################################
      - name: Build usuarios JAR
        run: |
          cd MicroUsuarios/MicroUsuarios
          mvn -B package -DskipTests

      - name: Build usuarios Docker image
        run: docker build -t ${{ secrets.ECR_REGISTRY }}/usuarios:latest ./MicroUsuarios/MicroUsuarios

      ###############################################################
      # 4. LOGIN TO AWS
      ###############################################################
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
              | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      ###############################################################
      # 5. PUSH DOCKER IMAGES TO ECR
      ###############################################################
      - name: Push carrito image
        run: docker push ${{ secrets.ECR_REGISTRY }}/carrito:latest

      - name: Push core image
        run: docker push ${{ secrets.ECR_REGISTRY }}/core:latest

      - name: Push usuarios image
        run: docker push ${{ secrets.ECR_REGISTRY }}/usuarios:latest
